### ISSUE TITLE
Photobrowser

### ISSUE THREAD

**Issue by SouhailJebali** [Mobideck/appdeck#1]
There is an issue with the Photobrowser. It does not work properly when the image url is relative (it works fine with abolute url's)
exp :
here it works : http://app.jeuxvideo-live.com/ps3/themes/jeux/trickshotting-2872
here isn't working : http://app.jeuxvideo-live.com/jeux-video/life-is-strange/images/

**Comment by Mobideck** [comment]
problem is now fixed.

relative URLs are now resolved on page side.
