### ISSUE TITLE
iOS AppDeck Build stuck on Waiting in Queue

### ISSUE THREAD

**Issue by HeavyGroovez** [Mobideck/appdeck#102]
Been stuck in queue for over an hour waiting for iOS build. Is this normal ?

I have been able to create several Android AppDeck builds today without any problem.

EDIT 18-01-2018 : The iOS build feature is not working at all. It fetches the build info then just sits on an async request waiting for a callback from the server (which never happens)

**Comment by mhdax** [comment]
I have the exact same problem.

**Comment by HeavyGroovez** [comment]
Build now shows buttons for appstore.ipa/simulator and build log but the .ipa does not hook to any file. Log shows the build completed.

**Comment by mdekermadec** [comment]
Hello, we are working on solving all building issues.

Can you ask for a new build please ? if it is still not working, can you tell me the name of your app so that I can check myself ?

**Comment by HeavyGroovez** [comment]
Build has completed successfully and the link to the .ipa file is now available.
