### ISSUE TITLE
Certificate expires to soon

### ISSUE THREAD

**Issue by bakkertjebrood** [Mobideck/appdeck#11]
Hi guys,

I'm trying to upload the newly created apk at the Google developer console, but it keeps repeating that the generated certificate is expiring to soon. Any ideas how to solve this?

Thanks in advance!

**Comment by mdekermadec** [comment]
It seems that 10 year was too short period of time for keystore validity, we just configure it for 30 years now.

Could you generate a new keystore and try again ?

**Comment by bakkertjebrood** [comment]
Yes! Problem solved, thanks for that :)
