### ISSUE TITLE
Unable to start activity Componentinfo(<APKNAME>): java.lang.NullPointerException

### ISSUE THREAD

**Issue by bakkertjebrood** [Mobideck/appdeck#12]
Hi,

When running the newly created APK on several Android devices, the following error occurs: Unable to start activity Componentinfo(<APKNAME>): java.lang.NullPointerException. Any ideas?

![errorlog](https://cloud.githubusercontent.com/assets/11925329/8767794/8453695a-2e68-11e5-91f8-e431f785b8ce.png)

**Comment by mdekermadec** [comment]
I failed to reproduce this bug.

Maybe it has to do with the version of your Android system.

Could you send me more info at contact@appdeck.mobi ? (test account, Android Version)

**Comment by mdekermadec** [comment]
Thank you for the information it help.

There was a problem for Android < 4.4.

Now it is fixed, I make a test on Android 4.1 on your device and it was OK.

**Comment by bakkertjebrood** [comment]
Thank you for the fix. Tested it on multiple devices. Works!


*Webshops | Websites | Webservices*
Wenckebachlaan 34
9728 JJ Groningen
*T.* 06 11 87 16 43
*@* elmerbakker@gmail.com
*I.* www.elmerbakker.nl




2015-07-22 15:19 GMT+02:00 Mathieu De Kermadec <notifications@github.com>:
