### ISSUE TITLE
caching and expected format

### ISSUE THREAD

**Issue by bakkertjebrood** [Mobideck/appdeck#13]
What syntax do i use when implementing caching?

**Comment by mdekermadec** [comment]
There is two way of caching:

 - Cache: Each line is a regexp, if an URL match it, resource will be cached. ex:
```
/css/
/js/
.*jpg
static.domain.com
```
 - Embed: At compilation time, ressources are copied into your app, you must add one URL per line. ex:
```
http://www.domain.com/css/file.css
http://static.cdn.com/js/jquery.js
```
On iOS, you can check if a file is cached or not and how (embed vs cache) with the log window at the bottom.

On Android, you need to check the log of your phone by connecting it to your computer and Android Studio.

**Comment by bakkertjebrood** [comment]
Thanks for the info!
