### ISSUE TITLE
How to fix build? 

### ISSUE THREAD

**Issue by ixt1** [Mobideck/appdeck#17]
Build Log:
....
FAILURE: Build failed with an exception.

* Where:
Build file '/appdeckbuild/src/appdeck-android/app/build.gradle' line: 96

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot invoke method multiply() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by mdekermadec** [comment]
In you AppDeck Build configuration for Android, applicationID, versionCode and versionName were missing.

It was causing this error, now we setup a default value for this field and your app build is OK.

Also note that you can test your app using the AppDeck app available in AppStore and PlayStore.

It may be faster than rebuild your app each time.

Thank you for your report!
