### ISSUE TITLE
ios app doesn't open 

### ISSUE THREAD

**Issue by grahamgardiner** [Mobideck/appdeck#18]
HI 

I'm using IoS 9 beta on my iPhone 6 and I can;t get the app to open. 

is this a common issue on IoS 9 ? 

Thanks 

Graham

**Comment by mdekermadec** [comment]
Are you testing using AppDeck app on AppStore or from source code ?

Is it via iOS Simulator or real device ?

**Comment by grahamgardiner** [comment]
Hi

From a real device.....

Thanks

Graham


ᐧ

Thanks & Regards

*Graham*


Graham Gardiner

0203 488 0009  : 0759 553 5200 : Twitter <http://twitter.com/grahamgardiner>


Aspiren <http://aspiren.org> : First Thursday London
<http://firstthursdaylondon.com>: LIMtool <http://limtool.com> : OurCamden
<http://ourcamden.org>

71 Tonbridge Street

Kings Cross

London

WCIH 9DZ

**Comment by mdekermadec** [comment]
There is a bug between iOS9 and AppDeck.

This will be fixed ASAP.

Did you see that on AppDeck Cloud Services there is an online iOs emulator ?

By the time we fix this it could help you test your app.

**Comment by grahamgardiner** [comment]
Great thanks for your help

Will check out the simulator in the meantime

Cheers.

Graham

On Monday, August 10, 2015, Mathieu De Kermadec <notifications@github.com>
wrote:

> There is a bug between iOS9 and AppDeck.
>
> This will be fixed ASAP.
>
> Did you see that on AppDeck Cloud Services there is an online iOs emulator
> ?
>
> By the time we fix this it could help you test your app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mobideck/appdeck/issues/18#issuecomment-129604934>.
>


-- 
Thanks & Regards

*Graham*


Graham Gardiner

0203 488 0009  : 0759 553 5200 : Twitter <http://twitter.com/grahamgardiner>


Aspiren <http://aspiren.org> : First Thursday London
<http://firstthursdaylondon.com>: LIMtool <http://limtool.com> : OurCamden
<http://ourcamden.org>

71 Tonbridge Street

Kings Cross

London

WCIH 9DZ
