### ISSUE TITLE
Sending passwords in plain text?

### ISSUE THREAD

**Issue by markcipolla** [Mobideck/appdeck#19]
Thanks for creating an account on AppDeck!

Thank you for register to AppDeck!

Here is your new account information:

Username: mark@markcipolla.com
Password: [REDACTED]

----------------------------------------------------------

That's a huge security no-no.

**Comment by mdekermadec** [comment]
Yes, When you create your AppDeck Cloud Services account, your credential are send in plain text by email (but not stored in plain text in our database).

This should and will be changed in the future. Thanks for opening this issue.

**Comment by mdekermadec** [comment]
It's fixed.
