### ISSUE TITLE
android app package file is invalid

### ISSUE THREAD

**Issue by iryna7** [Mobideck/appdeck#20]
Hi, as soon as i install the apk file on my phone, it shows 'package file is invalid' something like that. any ideas? thanks in advance.

**Comment by mdekermadec** [comment]
There was an error with applicationID, it must be something like:

com.site.name

(two dots)

If not, it will create this error when you try to install apk.

I create a rules in AppDeck Cloud Services that make sure applicationId have the right form. Your apt should be OK now.

**Comment by iryna7** [comment]
Thanks a lot.
