### ISSUE TITLE
Apk file seems too big

### ISSUE THREAD

**Issue by astraura** [Mobideck/appdeck#22]
One or two page web app built size is around 45 MBs in apk file which seems high.  Project name:  Match Stars
astraura

**Comment by mdekermadec** [comment]
The apk you are talking about is an universal build which contain all subversion of the app:

 - x86 for android (crosswalk) < 4.4:  23 mo
 - arm for android (crosswalk) < 4.4 : 23 mo
 - x86 and arm >= 4.4 : 7.7 mo

This universal version is uses to distribute your app from outside Play Store.

For most users, final version of the app they will download from Play Store will only be 7.7 mo.

For users with old phone apk will be bigger: 23 mo as we need to embed in the app crosswalk as an alternative webview. (webview for android < 4.4 are not very efficient).
