### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by fis-it** [Mobideck/appdeck#26]
Hello,

How it is possible to add a splash screen during the loading of the app?

Thank you

**Comment by mdekermadec** [comment]
Hello,

on iOS, system show an image embed in your app during the loading of the app.
AppDeck automatically create an image based on your app logo and icon.

To change them:

Go to your appdeck cloud services account, in app configuration > Build > Extra Resources Ios:

Upload a zip file containing all loading image (one per iPhone/iPad screen resolution).

To help you with that, here is the zip file used for AppDeck test app:

http://storage.appdeck.mobi/file/218/extra_resources_ios/Archive.zip

On Android, As I recall, system offer no option to do that.

**Comment by fis-it** [comment]
Thank you very much for your fast answer. And it is the same for Android?

**Comment by mdekermadec** [comment]
For Android there is no official Splash screen functionalities.

I'm afraid that we will not implement one as it may make app starting slower.
