### ISSUE TITLE
App crash on galaxy Tab

### ISSUE THREAD

**Issue by fis-it** [Mobideck/appdeck#27]
I tried on a Android Phone with Android 4.1.2 and it's working well :) Then I install the same application (I also tried all apk, arm, crosswalk, uni) on the Tablett Galaxy Tab with the same version Android 4.1.2 and I get a black screen and then a popup tell me that the app as stopped.

**Comment by mdekermadec** [comment]
Thank for your report,

I take the liberty to test your application.

If I may, it seems that your app is using JQuery Mobile. To take advantage of AppDeck built in navigation system, you should disable JQuery Mobile ajax based Navigation system:

<script type="text/javascript">
// Disable ajax navigation
$.mobile.ajaxEnabled = false;
</script>

About the crash, Also I adjust proguard configuration, could you make another test ?

**Comment by fis-it** [comment]
Yes, I'm currently to adapt all templates, I let you know and thank you for your very prompt answers

**Comment by fis-it** [comment]
Seems to work now, Thank you
