### ISSUE TITLE
Sub domain link

### ISSUE THREAD

**Issue by ixt1** [Mobideck/appdeck#29]
Is it possible to sub domain links (like ex. "s1.domain.com", application domain is "domain.com") on click to open in application, not to suggest to open with browser?

**Comment by mdekermadec** [comment]
Hello,

It should be possible using: "Advanced" > "Other Domain" configuration.

Add:

.*\.domain\.com

Can you tell me if it works for you ?

**Comment by ixt1** [comment]
Thanks a lot for your help :)
.*.domain.com work perfect for subdomains
