### ISSUE TITLE
apk

### ISSUE THREAD

**Issue by khirul** [Mobideck/appdeck#36]
is possible to download apk for self distribute?

**Comment by mdekermadec** [comment]
If by "Self Distribute" you mean outside Play Store, Yes sure.

In AppDeck cloud Build, you will have a link named "app preview".

Go there and download the APK, this will be a special version of the APK which include all app version (ARM, X86 and 4.4+).

Size will be bigger than app in Play Store but for testing purpose this is OK.

**Comment by khirul** [comment]
thank you very much
