### ISSUE TITLE
App without top bar

### ISSUE THREAD

**Issue by SagiRelin** [Mobideck/appdeck#39]
Hi,

Can i remove a topbar? I already have a responsive site with topbar

**Comment by mdekermadec** [comment]
Hello,

The aim of AppDeck is to offer native implementations of Top Bar (with buttons), Menu (left/right), Animation, Network.

It allow better performance and reliability then HTML5 implementation.

It also allow your app to look like an app as we are using custom implementation of iOS and Android platform.

For instance when network is down AppDeck allow your application function properly.

For this reason, for the moment we decided to stick to this implementation: no possibility to remove TopBar.
Maybe in the future.
