### ISSUE TITLE
Advertising on AppDeck Cloud Services

### ISSUE THREAD

**Issue by subvert** [Mobideck/appdeck#43]
When I click on "Enable Ads" on AppDeck Cloud Services, the setting doesnt stay on Enabled.
When navigate away from the Ads configuration screen and go back, it is turned off again?

**Comment by mdekermadec** [comment]
This should be because of AdBlock ...

**Comment by subvert** [comment]
Thank you, I disabled AdBlock and I was able to activate Advertising.

I requested a new build of the app and published it to Google Store, however I dont see any Ads appear when I run the app? Do I need to activate anything else for the Ads to work?

**Comment by Mobideck** [comment]
Ads should arrived a few days after you publish your app to AppStore.
