### ISSUE TITLE
Can I disable "pull up to refresh ?"

### ISSUE THREAD

**Issue by rwanito** [Mobideck/appdeck#54]
Can I disable the pull up effect to refresh ?
Because when I'm using a google maps, when I pull up, my device refreshes whereas I want to move my map.

Thanks !

**Comment by RoboKopf** [comment]
You can disable pull to refresh with a meta:

<meta name="appdeck-disable-pulltorefresh" content="true">

or with javascript:

app.pulltorefresh.enable();
app.pulltorefresh.disable();

**Comment by rwanito** [comment]
Thanks it works !
