### ISSUE TITLE
Appdeck applications and private key for facebook/twitter

### ISSUE THREAD

**Issue by rwanito** [Mobideck/appdeck#66]
Hi !
I'm trying to create a connection between facebook/twitter in my application. But, when we want try in the appdeck application it's "appdeck cloud service" which is used, not my application. But, it works when I compile an APK. 
In short, Isn't my application ( private key from social networks ) which is used in appdeck application.

Thanks!

**Comment by mdekermadec** [comment]
Most service API Key are embed in your application at compilation time.

So you must use AppDeck Cloud Services to use your own API Key. Official AppDeck app use our API Key and we can't change that.

**Comment by rwanito** [comment]
Ok ! Thanks for your reply !
So, It works very well !
