### ISSUE TITLE
Support de l'app indexing du contenu par Google

### ISSUE THREAD

**Issue by yannbug** [Mobideck/appdeck#8]
http://www.webrankinfo.com/dossiers/indexation/app-mobile

https://developers.google.com/app-indexing/webmasters/app

Il faudrait juste mettre ce qu'il faut dans le fichier manifest. Du côté du balisage du site je pourrais faire en sorte que le plugin pour WordPress s'en occupe.

**Comment by mdekermadec** [comment]
C'est disponible sur la dernière version d'appdeck si le api est fait via le AppDeck Cloud Services.
