### ISSUE TITLE
Request: Disable reload

### ISSUE THREAD

**Issue by AIMMOTH** [Mobideck/appdeck#84]
Our app is a fullscreen iframe of our site. It's no problem scrolling down but scrolling up will trigger the reload and reload the whole iframe which resets its state.

We would request the option to disable reload when dragging down the page.

Thanks

**Comment by RoboKopf** [comment]
You can do it with this meta tag:

meta name="appdeck-disable-pulltorefresh" content="true"

or this js:

app.pulltorefresh.enable();
app.pulltorefresh.disable();

**Comment by AIMMOTH** [comment]
Perfect, thanks!
