### ISSUE TITLE
Request: Get User ID from AppDeck API

### ISSUE THREAD

**Issue by AIMMOTH** [Mobideck/appdeck#85]
Currently it seems that the only way to get user ID by making an HTTP request to server and then read the header "AppDeck-User-ID". 
Instead of using this procedure, can't there be a AppDeck API call to get the user ID?

Also, I tried to use app.helper.ajax() to call my server but there was no "AppDeck-User-ID" header. How should I do the request? 

Thanks 

Edit: Does the AppDeck preview app send this or does it only send the header with the real app?

**Comment by mdekermadec** [comment]
I think this is an interesting request.

We will add this in our API.

About the header, you should see this header in all request (normal, ajax with or without helper).

If it is not there ... this is a bug !

**Comment by AIMMOTH** [comment]
Cool! Is there release notes or a date for this release?
