### ISSUE TITLE
Image URL for Push notification

### ISSUE THREAD

**Issue by AIMMOTH** [Mobideck/appdeck#88]
When using the form for a manuell PUSH notification there's input for image URL.
http://cloud.appdeck.mobi/app/xxx/push/send

But in the documentation there's nothing about this image URL. What is the parameter for image URL when using the HTTP API? 
http://www.appdeck.mobi/doc/advanced_push

**Comment by mdekermadec** [comment]
Parameter is image_url.

It only works on android.

I will update configuration.
