### ISSUE TITLE
Can't download .ipa and AppDeck-Simulator.zip Folder is empty

### ISSUE THREAD

**Issue by SimeonLukas** [Mobideck/appdeck#99]
Hello,
I'm not able to download an .ipa File from the Build Section after renewing the Provisining Profile of my App. The buildlog says:

Export for AppStore
xcodebuild -exportArchive -exportFormat IPA -archivePath '/appdeckbuild/src/appdeck-ios/build/AppDeck.xcarchive' -exportPath '/appdeckbuild/src/appdeck-ios/build/AppDeck-AppStore.ipa' -exportProvisioningProfile '20171120 AppStore impuls AO' 2>&1 
--- xcodebuild: WARNING: -exportArchive without -exportOptionsPlist is deprecated
error: archive not found at path '/appdeckbuild/src/appdeck-ios/build/AppDeck.xcarchive'
** EXPORT FAILED **

Please help!

Greetings from Bavaria

**Comment by mdekermadec** [comment]
Hello, it should be ok now. Thanks for this report.
